artist = "KünstlerIn"
autor = "AutorIn"
autoren = "AutorInnen"
autotranslatefrom = "automatisch übersetzt aus dem"
back = "Zurück"
backtosearch = "Zurück zur Suche"
camera = "Kamera"
collection = "Sammlung"
correction = "Korrektur Datensatz"
deen = "deutschen"
document = "Dokument"
enen = "englischen"
erstellt = "erstellt von"
event = "Event"
eventcurator = "EventkuratorIn"
founditems = "Gefundene Objekte"
fren = "französischen"
impressum = "Impressum"
iten = "italienischen"
language = "Sprache"
medium = "Medium"
newentry = "Neuer Eintrag"
next = "Weiter"
performer = "PerformerIn"
search = "Suchen"
searchtext = "Suchtext"
signature = "Signatur"
test = "TestDE"
test-en = "TestEN"
titel = "Titel"
title = "Sammlungen Performance Kunst Schweiz"
voc_Abfall = "Abfall"
voc_Akrobatik = "Akrobatik"
voc_Aktion = "Aktion"
voc_Alltag = "Alltag"
"voc_Alltagsgegenstände" = "Alltagsgegenstände"
voc_Ambivalenzen = "Ambivalenzen"
voc_Appropriation = "Appropriation"
voc_Architektur = "Architektur"
voc_Artivismus = "Artivismus"
voc_Atelier = "Atelier"
voc_Audio = "Audio"
voc_Ausstellungsobjekt = "Ausstellungsobjekt"
voc_Ausstellungsraum = "Ausstellungsraum"
"voc_Automatisches Schreiben" = "Automatisches Schreiben"
"voc_Band - Schnur" = "Band - Schnur"
voc_Begegnung = "Begegnung"
voc_Behausung = "Behausung"
"voc_Bezüge" = "Bezüge"
voc_Bilderflut = "Bilderflut"
voc_Bildrechte = "Bildrechte"
voc_Biografie = "Biografie"
"voc_Body Art" = "Body Art"
voc_Butoh = "Butoh"
"voc_Bühne" = "Bühne"
"voc_Bühnentechnik" = "Bühnentechnik"
voc_Choreografie = "Choreografie"
voc_Club = "Club"
voc_Comic = "Comic"
voc_Destruktion = "Destruktion"
voc_Dienstleistungsperformance = "Dienstleistungsperformance"
"voc_Dokumentation einer Performance" = "Dokumentation einer Performance"
voc_Drag = "Drag"
voc_Duo = "Duo"
"voc_Elektronische Musik" = "Elektronische Musik"
voc_Emotionen = "Emotionen"
voc_Ensemble = "Ensemble"
voc_Ephemera = "Ephemera"
voc_Erinnerung = "Erinnerung"
"voc_Ernährung" = "Ernährung"
voc_Esswaren = "Esswaren"
voc_Explosion = "Explosion"
voc_Fake = "Fake"
voc_Familie = "Familie"
voc_Farbe = "Farbe"
voc_Feminismus = "Feminismus"
voc_Feuer = "Feuer"
voc_Figur = "Figur"
voc_Fiktion = "Fiktion"
voc_Film = "Film"
voc_Fluxus = "Fluxus"
"voc_Flüssigkeiten" = "Flüssigkeiten"
"voc_Food Art" = "Food Art"
"voc_Found Footage" = "Found Footage"
"voc_Fundstücke" = "Fundstücke"
voc_Gamekultur = "Gamekultur"
"voc_Gefässe" = "Gefässe"
voc_Gender = "Gender"
voc_Genres = "Genres"
voc_Gentrifizierung = "Gentrifizierung"
voc_Genuss = "Genuss"
"voc_Geräusche" = "Geräusche"
voc_Gesamtkunstwerk = "Gesamtkunstwerk"
voc_Gesten = "Gesten"
voc_Gruppe = "Gruppe"
voc_Handlungen = "Handlungen"
voc_Handlungsvollzug = "Handlungsvollzug"
voc_Happening = "Happening"
voc_Heimat = "Heimat"
voc_Historie = "Historie"
"voc_Identität" = "Identität"
"voc_Identitätspolitiken" = "Identitätspolitiken"
voc_Illusion = "Illusion"
voc_Improvisation = "Improvisation"
"voc_Individuelle Mythologien" = "Individuelle Mythologien"
voc_Inszenierung = "Inszenierung"
voc_Intervention = "Intervention"
voc_Interview = "Interview"
voc_Kamera = "Kamera"
voc_Kapitalismus = "Kapitalismus"
voc_Karaoke = "Karaoke"
voc_Kinder = "Kinder"
voc_Klangkunst = "Klangkunst"
voc_Klebeband = "Klebeband"
voc_Klischee = "Klischee"
voc_Kollektiv = "Kollektiv"
voc_Kolonialismuskritik = "Kolonialismuskritik"
voc_Kommunikation = "Kommunikation"
voc_Konflikt = "Konflikt"
voc_Kontrolle = "Kontrolle"
"voc_Kostüm" = "Kostüm"
voc_Kraft = "Kraft"
voc_Kreislauf = "Kreislauf"
"voc_Kunst und Leben" = "Kunst und Leben"
voc_Kunstfigur = "Kunstfigur"
voc_Kunstmarkt = "Kunstmarkt"
"voc_Körper als Material" = "Körper als Material"
"voc_Körper und Objekt" = "Körper und Objekt"
"voc_Körper und Raum" = "Körper und Raum"
"voc_Körperbilder" = "Körperbilder"
"voc_Körpererfahrung" = "Körpererfahrung"
"voc_Körperverlängerungen" = "Körperverlängerungen"
"voc_Künstlerdokumentation" = "Künstlerdokumentation"
"voc_Land Art" = "Land Art"
voc_Landschaft = "Landschaft"
voc_Langzeitperformance = "Langzeitperformance"
"voc_Lecture Performance" = "Lecture Performance"
voc_Licht = "Licht"
voc_Literatur = "Literatur"
"voc_Living Sculpture" = "Living Sculpture"
voc_Lockdown = "Lockdown"
voc_Luft = "Luft"
"voc_Luft/Atem" = "Luft/Atem"
voc_Macht-Ohnmacht = "Macht-Ohnmacht"
"voc_Making of" = "Making of"
voc_Malerei = "Malerei"
voc_Malperformance = "Malperformance"
voc_Maschine = "Maschine"
voc_Maske = "Maske"
voc_Masse = "Masse"
voc_Massenmedien = "Massenmedien"
voc_Materialien = "Materialien"
voc_Materialtyp = "Materialtyp"
voc_Materialuntersuchung = "Materialuntersuchung"
"voc_Mediale Übertragung" = "Mediale Übertragung"
voc_Medienecho = "Medienecho"
voc_Medizin = "Medizin"
"voc_Mensch und Tier" = "Mensch und Tier"
voc_Migration = "Migration"
voc_Mittel = "Mittel"
voc_Mode = "Mode"
voc_Multimediaperformance = "Multimediaperformance"
voc_Museum = "Museum"
voc_Musik = "Musik"
voc_Musikinstrumente = "Musikinstrumente"
voc_Musikperformance = "Musikperformance"
voc_Mythen = "Mythen"
"voc_Märchen" = "Märchen"
voc_Nacktheit = "Nacktheit"
voc_Nacktperformance = "Nacktperformance"
voc_Narration = "Narration"
"voc_Nationalität" = "Nationalität"
voc_Natur-Kultur = "Natur-Kultur"
voc_Normen = "Normen"
voc_Paar = "Paar"
voc_Papier = "Papier"
voc_Parallelaktionen = "Parallelaktionen"
voc_Partizipation = "Partizipation"
voc_Performance = "Performance"
"voc_Performance/Aktion für die Kamera" = "Performance/Aktion für die Kamera"
voc_Performancebeschreibung = "Performancebeschreibung"
voc_Pflanzen = "Pflanzen"
"voc_Physical Theatre" = "Physical Theatre"
voc_Players = "Players"
voc_Politik = "Politik"
voc_Popkultur = "Popkultur"
"voc_Postmoderner Tanz" = "Postmoderner Tanz"
voc_Privatraum = "Privatraum"
voc_Projektion = "Projektion"
"voc_Präpariertes Performanceobjekt" = "Präpariertes Performanceobjekt"
voc_Publikation = "Publikation"
voc_Publikum = "Publikum"
"voc_Qualitäten" = "Qualitäten"
voc_Queer = "Queer"
voc_Reisen = "Reisen"
voc_Religion = "Religion"
voc_Reperformance = "Reperformance"
voc_Ritual = "Ritual"
"voc_Räume" = "Räume"
voc_Schmerz = "Schmerz"
voc_Schule = "Schule"
voc_Score = "Score"
voc_Setting = "Setting"
"voc_Setting/Installation" = "Setting/Installation"
voc_Sex = "Sex"
voc_Show = "Show"
"voc_Site Specific" = "Site Specific"
voc_Skulptur = "Skulptur"
"voc_Social Media" = "Social Media"
voc_Song = "Song"
"voc_Soziale Skulptur" = "Soziale Skulptur"
voc_Spaziergang = "Spaziergang"
voc_Spiegelung = "Spiegelung"
voc_Sprache = "Sprache"
voc_Spur = "Spur"
voc_Stimme = "Stimme"
voc_Strassentheater = "Strassentheater"
voc_Stuhl = "Stuhl"
"voc_Szenische Performance" = "Szenische Performance"
"voc_Tableau Vivant" = "Tableau Vivant"
voc_Tanzfilm = "Tanzfilm"
voc_Tanzperformance = "Tanzperformance"
voc_Text = "Text"
voc_Textilien = "Textilien"
voc_Theaterperformance = "Theaterperformance"
voc_Themen = "Themen"
voc_Tiere = "Tiere"
voc_Tisch = "Tisch"
voc_Tod = "Tod"
voc_Trio = "Trio"
voc_Umnutzung = "Umnutzung"
voc_Unterhaltung = "Unterhaltung"
voc_Veranstaltungsdokumentation = "Veranstaltungsdokumentation"
"voc_Vergänglichkeit" = "Vergänglichkeit"
voc_Verletzlichkeit = "Verletzlichkeit"
voc_Vermittlungsprojekt = "Vermittlungsprojekt"
voc_Videokunst = "Videokunst"
"voc_Virtueller Raum" = "Virtueller Raum"
voc_Volkskultur = "Volkskultur"
voc_Wahrnehmung = "Wahrnehmung"
voc_Wert = "Wert"
voc_Wissenschaft = "Wissenschaft"
voc_Workshop = "Workshop"
voc_Zirkus = "Zirkus"
voc_absurd = "absurd"
voc_aktivieren = "aktivieren"
voc_arbeiten = "arbeiten"
voc_balancieren = "balancieren"
voc_beissen = "beissen"
"voc_berühren" = "berühren"
voc_bildhaft = "bildhaft"
voc_blind = "blind"
voc_essen = "essen"
"voc_essen und trinken" = "essen und trinken"
voc_experimentell = "experimentell"
voc_expressiv = "expressiv"
voc_gehen = "gehen"
voc_giessen = "giessen"
voc_grotesk = "grotesk"
voc_hantieren = "hantieren"
voc_humorvoll = "humorvoll"
"voc_hängen" = "hängen"
voc_kochen = "kochen"
voc_konzeptuell = "konzeptuell"
voc_kopieren = "kopieren"
voc_kreisen = "kreisen"
voc_langsam = "langsam"
voc_liegen = "liegen"
voc_meditativ = "meditativ"
voc_minimalistisch = "minimalistisch"
voc_monumental = "monumental"
voc_obsessiv = "obsessiv"
voc_poetisch = "poetisch"
voc_posieren = "posieren"
voc_prozessual = "prozessual"
voc_repetierend = "repetierend"
voc_riskant = "riskant"
voc_rot = "rot"
voc_sammeln = "sammeln"
voc_schlafen = "schlafen"
voc_schneiden = "schneiden"
voc_schreiben = "schreiben"
voc_schwarz-weiss = "schwarz-weiss"
voc_singen = "singen"
voc_sitzen = "sitzen"
"voc_sphärisch" = "sphärisch"
voc_spielerisch = "spielerisch"
voc_stehen = "stehen"
voc_stumm = "stumm"
voc_symbolisch = "symbolisch"
voc_tanzen = "tanzen"
voc_transformieren = "transformieren"
voc_verbinden = "verbinden"
voc_weiss = "weiss"
voc_wild = "wild"
"voc_wortwörtlich" = "wortwörtlich"
"voc_wütend" = "wütend"
voc_zeichenhaft = "zeichenhaft"
"voc_zärtlich" = "zärtlich"
"voc_Öffentlicher Raum" = "Öffentlicher Raum"
"voc_Ökologie" = "Ökologie"
"voc_Übersetzung" = "Übersetzung"
year = "Jahr"
