back = "Back"
collection = "Collection"
founditems = "Found Items"
language = "Language"
next = "Next"
search = "Search"
searchtext = "Search Text"
test = "Test"
title = "Collections of Swiss Performance Art"
