name = "ink"
logfile = ""
loglevel = "DEBUG"
notemplatecache = true
localaddr = ":8445"
externaladdr = "https://localhost:8445"
searchaddr = "https://localhost:8445"
detailaddr = "https://localhost:8445"

zoomonly = false

openaiapikey = "%%OPENAI_API_KEY%%"

#templates = "data/web/templates/ink"
#staticfiles = "data/web/static"
datadir = "c:/temp/performance"
#mediaserverbase = "https://localhost:8446"
mediaserverbase = "https://ba14ns21403-sec1.fhnw.ch/mediasrv"
mediaserverkey = "%%MEDIASERVER_KEY%%"
mediaservertokenexp = "6h"

jwtkey = "%%JWTKEY%%" # ":Xf/#|IKYrDsNi4]LN*o(W7;:"
jwtalg = "HS512"

fieldmapping.author = "[persons].name.keyword"

facetinclude = []
facetexclude = ["vww:*"]

[[clients]]

[login]
jwtkey = "%%LOGIN_JWTKEY%%" # ":Xf/#|IKYrDsNi4]LN*o(W7;:"
jwtalg = ["HS256","HS384","HS512"]
linktokenexp = "1h"
#url = "https://intern.hgk.fhnw.ch/ango/shib/auth/localhost"
url = "https://intern.hgk.fhnw.ch/ango/oidc/auth/localhost"
issuer = "auth.hgk.fhnw.ch/localhost"


[[locations]]
group = "net/local"
networks = ["127.0.0.1/32", "::1/128"]

[[locations]]
group = "location/fhnw"
networks = ["10.0.0.0/8", "192.168.0.0/16", "147.86.0.0/16"]

[[locations]]
group = "net/fhnw"
networks = ["10.0.0.0/8", "192.168.0.0/16", "147.86.0.0/16"]

[[locations]]
group = "location/memoriav"
networks = ["62.2.199.158/32"]

[[locations]]
group = "net/bfh"
networks = ["147.87.0.0/16", "5.35.244.248/32", "213.200.195.102/32", "193.5.80.0/21", "2a07:6b40::/29", "2001:620:500::/48"]

[mediaserver]
localaddr = "localhost:8446"
externaladdr = "https://localhost:8446"
basedir = "performance/mediaserver"

[revcat]
endpoint = "https://localhost:8443/graphql"
insecure = true
#apikey = "%%REVCAT_APIKEY%%"
apikey = "%%REVCAT_APIKEY_INK%%"

[directus]
baseurl = "https://cms.basel-collections.ch"
token = "%%DIRECTUS_TOKEN%%"
cachetime = "10s"
catalogid = 2

[locale]
default = "de"
folder = ""
available = ["de", "fr", "it", "en"]


[[collections]]
id = 1
identifier = "cat:\"zotero2!!ACT Performance Festival\""
title = "ACT Basel"
url = "https://www.act-perform.net/"
image = "act_klein.png"
contact = "Marion Ritzmann, Hannah Weinberger"

[[collections]]
id = 2
identifier = "cat:\"forms2!!diplom\""
title = "Next Generation"
url = "https://nextgeneration.hgk.fhnw.ch/"
contact = "kommunikation.hgk@fhnw.ch"

[[collections]]
id = 3
identifier = "cat:\"zotero2!!Werke\""
title = "Forschungsdaten & Publikationen"
url = "https://mediathek.hgk.fhnw.ch/"
image = "act_klein.png"
contact = "mediathek.hgk@fhnw.ch"

[[collections]]
id = 5
identifier = "cat:\"zotero2!!Werke!!Data-Publications!!CulturalSpace&Design - Research\""
title = "Cultural Spaces and Design"
url = "https://mediathek.hgk.fhnw.ch/front/#/de/bestaende/32"
image = "act_klein.png"
contact = "Regine Halter, Catherine Walthard, Anka Falk"


[[collections]]
id = 6
identifier = "cat:\"zotero2!!Werke!!Memory Full\""
title = "Memory Full"
url = "https://mediathek.hgk.fhnw.ch/front/#/de/bestaende/31"
image = "act_klein.png"
contact = "Meret Ernst"

[[collections]]
id = 7
identifier = "cat:\"zotero2!!Videonetzwerke\""
title = "Videonetzwerke"
url = "https://mediathek.hgk.fhnw.ch/collection/videonetzwerke"
image = "act_klein.png"
contact = "Point de Vue, Piet Esch, Stefanie Bräuer"

[[collections]]
id = 8
identifier = "cat:\"zotero2!!Videowochen im Wenkenpark\""
title = "Video Wochen Wenkenpark"
url = "https://mediathek.hgk.fhnw.ch/front/#/de/bestaende/5"
image = "act_klein.png"
contact = "mediathek.hgk@fhnw.ch"

[[collections]]
id = 9
identifier = "cat:\"zotero2!!Film + Design\""
title = "Film + Design"
url = "https://mediathek.hgk.fhnw.ch/front/#/de/bestaende/28"
image = "act_klein.png"
contact = "Marion Ritzmann, Hannah Weinberger"

[[collections]]
id = 10
identifier = "cat:\"zotero2!!PCB_Basel\""
title = "Performance Chronik Basel"
url = "https://www.performancechronikbasel.ch/"
image = "performance_chronik_klein.png"
contact = "Muda Mathis, Sabine Gebhardt Fink, Margarit von Büren"

[[collections]]
id = 11
identifier = "cat:\"zotero2!!Performance Art!!6x2 Performance-Duos\""
title = "6x2 Performance-Duos"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/23"
image = "6x2duos_klein.png"
contact = "Pascale Grau, Claudia Grimm"

[[collections]]
id = 12
identifier = "cat:\"zotero2!!Performance Art!!Together Elsewhere\""
title = "Together Elsewhere"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/26"
image = "together_elsewhere_klein.png"
contact = "Gisela Hochuli (PANCH), Pavana Reid (PAB)"

[[collections]]
id = 13
identifier = "cat:\"bangbang\""
title = "Revolving Histories"
url = "https://revolving-histories.ch/"
image = "revolving_histories_klein.png"
contact = "Sabine Gebhardt Fink, Muda Mathis, Chris Regn, Andrea Saemann, Margarit von Büren"

[[collections]]
id = 14
identifier = "cat:\"zotero2!!Performance Art!!Doce en Diciembre\""
title = "Doce en Diciembre"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/25"
image = "doce_en_diciembre_klein.png"
contact = "Barbara Naegelin, Chris Regn, Andrea Saemann"

[[collections]]
id = 15
identifier = "cat:\"zotero2!!Archive des Ephemeren\""
title = "Archive des Ephemeren"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/12"
image = "archive_des_ephemeren_klein.png"
contact = "Pascale Grau, Margarit von Büren, PANCH"

[[collections]]
id = 16
identifier = "cat:\"zotero2!!Interviews Archiv Performativ\""
title = "Interviews: Archiv Performativ "
url = "http://archivperformativ.zhdk.ch/"
image = "interviews_archiv_performativ_klein.png"
contact = "Pascale Grau, Margarit von Büren"

[[collections]]
id = 17
identifier = "cat:\"zotero2!!Perf en Bref\""
title = "Perf En Bref"
url = "https://apresperf.ch/category/interviews"
image = "perf_en_bref_klein.png"
contact = "Chris Regn, Andrea Saemann"

[[collections]]
id = 18
identifier = "cat:\"zotero2!!Kaskadenkondensator_ Basel!!Kasko-Videodokumentationen\""
title = "Kasko"
url = "https://www.kasko.ch/"
image = "kasko_klein.png"
contact = "Pascale Grau, Chris Regn"

[[collections]]
id = 19
identifier = "cat:\"iid-Arbeit\""
title = "IID Arbeiten"
url = ""
image = ""
contact = "Tabea Lurk"

[[collections]]
id = 20
identifier = "cat:\"iid-Modul\""
title = "IID Module"
url = ""
image = ""
contact = "Tabea Lurk"

[[collections]]
id = 21
identifier = "cat:\"zotero2!!Werke!!Hochschule für Musik\""
title = "Hochschule für Musik"
url = ""
image = ""
contact = "Tabea Lurk"

[[collections]]
id = 22
identifier = "cat:\"zotero2!!Werke!!Motet Cycles\""
title = "Motet Cycle"
url = ""
image = ""
contact = "Tabea Lurk"
