logfile = ""
loglevel = "DEBUG"

localaddr = "localhost:8445"
externaladdr = "https://localhost:8445"
searchaddr = "https://localhost:8445"
detailaddr = "https://localhost:8445"

zoomonly = false

openaiapikey = "%%OPENAI_API_KEY%%"

templates = "data/web/templates"
staticfiles = "data/web/static"
datadir = "/temp/performance"
#mediaserverbase = "https://localhost:8446"
mediaserverbase = "https://ba14ns21403-sec1.fhnw.ch/mediasrv"

fieldmapping.author = "persons.name.keyword"

[mediaserver]
localaddr = "localhost:8446"
externaladdr = "https://localhost:8446"
basedir = "/temp/performance/mediaserver"

[revcat]
endpoint = "https://localhost:8443/graphql"
insecure = true
apikey = "%%REVCAT_APIKEY%%"

[directus]
baseurl = "https://cms.basel-collections.ch"
token = "%%DIRECTUS_TOKEN%%"
cachetime = "10s"
catalogid = 2

[locale]
default = "de"
folder = ""
available = ["de", "fr", "it", "en"]


[[collections]]
id = 1
identifier = "cat:\"zotero2!!PCB_Basel\""
title = "Performance Chronik Basel"
url = "https://www.performancechronikbasel.ch/"
image = "performance_chronik_klein.png"
contact = "Muda Mathis, Sabine Gebhardt Fink, Margarit von B端ren"

[[collections]]
id = 5
identifier = "cat:\"zotero2!!ACT Performance Festival\""
title = "ACT Basel"
url = "https://www.act-perform.net/"
image = "act_klein.png"
contact = "Marion Ritzmann, Hannah Weinberger"

[[collections]]
id = 10
identifier = "cat:\"zotero2!!Performance Art!!6x2 Performance-Duos\""
title = "6x2 Performance-Duos"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/23"
image = "6x2duos_klein.png"
contact = "Pascale Grau, Claudia Grimm"

[[collections]]
id = 11
identifier = "cat:\"zotero2!!Archive des Ephemeren\""
title = "Archive des Ephemeren"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/12"
image = "archive_des_ephemeren_klein.png"
contact = "Pascale Grau, Margarit von B端ren, PANCH"

[[collections]]
id = 27
identifier = "cat:\"zotero2!!Performance Art!!Together Elsewhere\""
title = "Together Elsewhere"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/26"
image = "together_elsewhere_klein.png"
contact = "Gisela Hochuli (PANCH), Pavana Reid (PAB)"

[[collections]]
id = 28
identifier = "cat:\"bangbang\""
title = "Revolving Histories"
url = "https://revolving-histories.ch/"
image = "revolving_histories_klein.png"
contact = "Sabine Gebhardt Fink, Muda Mathis, Chris Regn, Andrea Saemann, Margarit von B端ren"

[[collections]]
id = 55
identifier = "cat:\"zotero2!!Performance Art!!Doce en Diciembre\""
title = "Doce en Diciembre"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/25"
image = "doce_en_diciembre_klein.png"
contact = "Barbara Naegelin, Chris Regn, Andrea Saemann"

[[collections]]
id = 57
identifier = "cat:\"zotero2!!Interviews Archiv Performativ\""
title = "Interviews: Archiv Performativ "
url = "http://archivperformativ.zhdk.ch/"
image = "interviews_archiv_performativ_klein.png"
contact = "Pascale Grau, Margarit von B端ren"

[[collections]]
id = 59
identifier = "cat:\"zotero2!!Perf en Bref\""
title = "Perf En Bref"
url = "https://apresperf.ch/category/interviews"
image = "perf_en_bref_klein.png"
contact = "Chris Regn, Andrea Saemann"

[[collections]]
id = 60
identifier = "cat:\"zotero2!!Kaskadenkondensator_ Basel!!Kasko-Videodokumentationen\""
title = "Kasko"
url = "https://www.kasko.ch/"
image = "kasko_klein.png"
contact = "Pascale Grau, Chris Regn"